name: Build Backend Spring Boot and Push Docker Image #Nombre del workflow

on:
  push: #este workflow se activara cada vez que yo haga un push al repositorio
    branches:
      - main 
     # - dev
  #pull_request:
  #  branches:
   #   - dev

jobs: #conjunto de tareas
  build:
    runs-on: ubuntu-latest #el SO necesario para poder compilar el proyecto

    steps:
      - name: Check out the code
        uses: actions/checkout@v3 #esto descarga el codigo del repositorio en el entorno de ejecuci√≥n, para que los siguientes pasos tengan acceso al codigo fuente

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: '17' #La version de java que estoy usando
          distribution: 'temurin' #especifica la distribucion de JDK

      - name: Dando permisos de ejecucion para Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build JAR
        run: ./mvnw clean package -DskipTests #aca estoy construyendo el jar de mi proyecto

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t luisorihuela92/secret-key-backend:latest .
#          docker build -t luisorihuela92/secret-key-backend:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push luisorihuela92/secret-key-backend:latest
#          docker push luisorihuela92/secret-key-backend:${{ github.sha }}
